name: "[test] isort-fix"

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./actions/isort-fix
        id: isort
        with:
          path: 'actions/'

      - name: Mostrar output
        run: echo "changed=${{ steps.isort.outputs.changed }}"
