name: app-distribution

on:
  workflow_call:
    inputs:
      clear-cache:
        description: "'true' pra limpar o cache do Nuitka antes de rodar (rebuild limpo)"
        required: false
        type: boolean
        default: false

jobs:
  validation:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      changed: ${{ steps.check.outputs.changed }}
      version: ${{ steps.check.outputs.version }}
    steps:
      - uses: actions/checkout@v7

      - name: check-branch
        uses: Maria-Cacau/Maria-Cacau-Actions/actions/git/branch-check@v2

      - id: check
        name: check-version
        uses: Maria-Cacau/Maria-Cacau-Actions/actions/check-version@v2
        env:
          GH_TOKEN: ${{ github.token }}

  app-distribution:
    needs: validation
    if: needs.validation.outputs.changed == 'true'
    runs-on: windows-latest
    permissions:
      actions: write
    outputs:
      exe-path: ${{ steps.build.outputs.exe-path }}
      app-name: ${{ steps.build.outputs.app-name }}
    steps:
      - uses: actions/checkout@v7

      - id: build
        name: app-build
        uses: Maria-Cacau/Maria-Cacau-Actions/actions/app-build@v2
        with:
          clear-cache: ${{ inputs.clear-cache }}

      - uses: actions/upload-artifact@v7
        with:
          name: exe
          path: ${{ steps.build.outputs.exe-path }}

  release-publish:
    needs: [validation, app-distribution]
    if: needs.validation.outputs.changed == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    steps:
      - uses: actions/checkout@v7

      - uses: actions/download-artifact@v8
        with:
          name: exe
          path: dist

      - id: zip
        name: to-zip
        uses: Maria-Cacau/Maria-Cacau-Actions/actions/to-zip@v2
        with:
          path: dist/${{ needs.app-distribution.outputs.app-name }}.exe

      - uses: Maria-Cacau/Maria-Cacau-Actions/actions/git/release-publish@v2
        with:
          version: ${{ needs.validation.outputs.version }}
          asset-path: ${{ steps.zip.outputs.zip-path }}
        env:
          GH_TOKEN: ${{ github.token }}

      - name: delete-test-tag
        uses: Maria-Cacau/Maria-Cacau-Actions/actions/git/tag-delete@v2
        with:
          version: ${{ needs.validation.outputs.version }}
        env:
          GH_TOKEN: ${{ github.token }}
